export { AdminDashboardComponent } from './admin-dashboard/admin-dashboard.component';
export { AdminOverviewComponent } from './admin-overview/admin-overview.component';
export { AdminQuizAddComponent } from './admin-quiz-add/admin-quiz-add.component';
export { AdminQuizzesComponent } from './admin-quizzes/admin-quizzes.component';
export { AdminSidebarNavComponent } from './admin-sidebar-nav/admin-sidebar-nav.component';
export { AdminStudentAddComponent } from './admin-student-add/admin-student-add.component';
export { AdminStudentDetailsComponent } from './admin-student-details/admin-student-details.component';
export { AdminStudentEditComponent } from './admin-student-edit/admin-student-edit.component';
export { AdminStudentsComponent } from './admin-students/admin-students.component';
