export { AboutComponent } from './about/about.component';
export { ContactComponent } from './contact/contact.component';
export { CurriculumComponent } from './curriculum/curriculum.component';
export { HeaderComponent } from './header/header.component'
export { HomeComponent } from './home/home.component'
export { LoginComponent } from './login/login.component'
export { NavbarComponent } from './navbar/navbar.component';
export { NotFoundPageComponent } from './not-found-page/not-found-page.component';
export { OnlineLessonComponent } from './online-lesson/online-lesson.component';
export { OnlineLessonsComponent } from './online-lessons/online-lessons.component';
export { UploadComponent } from './upload/upload.component';
export { WorksheetsComponent } from './worksheets/worksheets.component';
